---
title: "Puesta a punto"
description: |
  Instalación y ajustes para comenzar el curso
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```


## Dinámica de taller

Este taller está pensado para ser esencialmente práctico. La idea es exponer una presentación por módulo, en donde cada 3 o 4 conceptos se le dedicará un tiempo para poder ejercitar lo visto, previo a continuar con el siguiente contenido.

Se recomienda seguir las presentaciones durante la exposición ya que de ellas se extraerá el código, haciendo más ágil la cursada.



## Instalación de R

Asegurate de tener instalado R en tu computadora previo a comenzar el taller. Desde (R-project)[https://www.r-project.org/] vas a poder hacerte de R. 

**Sugerencia:** instalar (rtools)[https://cran.r-project.org/bin/windows/Rtools/], herramienta para poder trabajar con el paquete `tidyverse`.



## Instalación de Rstudio

Rstudio es la plataforma desde donde se trabajará durante todo el taller. Si bien debemos tener instalado R, el programa que se abrirá en cada clase y desde donde haremos los ejercicios es Rstudio.

(Descargar Rstudio)[https://www.rstudio.com/products/rstudio/download/#download]


## Descarga de Slack (versión escritorio)

Slack es una plataforma de intercambio que funciona como un chat-foro. Desde allí es posible concentrar la comunicación del curso, difundir material, código como también realizar consultas y respuestas de forma grupal.